# Generated by Django 4.1.5 on 2023-01-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacaolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacao',
            old_name='Funcionario_id',
            new_name='Funcionario',
        ),
        migrations.RenameField(
            model_name='relacao',
            old_name='Projeto_id',
            new_name='Projeto',
        ),
    ]
