# Generated by Django 4.1.5 on 2023-01-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacaolist', '0002_rename_funcionario_id_relacao_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relacao',
            table='Relacoes',
        ),
    ]
