# Generated by Django 4.1.5 on 2023-01-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetolist', '0001_initial'),
        ('funcionariolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacaoProjetoFuncionario',
            fields=[
                ('Relacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('Carga_horaria', models.FloatField()),
                ('Funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionariolist.funcionario')),
                ('Projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetolist.projeto')),
            ],
            options={
                'db_table': 'RelacoesProjetosFuncionarios',
            },
        ),
    ]
