# Generated by Django 4.1.5 on 2023-01-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionariolist', '0001_initial'),
        ('departamentolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('Projeto_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200, unique=True)),
                ('Horas_conclusao', models.FloatField()),
                ('Prazo_estimado', models.DateField()),
                ('Horas_realizadas', models.FloatField()),
                ('Ultimo_calculo_horas', models.DateField(auto_now_add=True)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentolist.departamento')),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionariolist.funcionario')),
            ],
            options={
                'db_table': 'Projetos',
            },
        ),
    ]
