# Generated by Django 4.1.5 on 2023-01-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='Supervisor',
        ),
    ]
