# Generated by Django 4.1.5 on 2023-01-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='Departamento_id',
            new_name='Departamento',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='Supervisor_id',
            new_name='Supervisor',
        ),
    ]
