# Generated by Django 4.1.5 on 2023-01-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='Horas_totais_realizadas',
            field=models.FloatField(default=0),
        ),
    ]
