# Generated by Django 4.1.5 on 2023-01-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetolist', '0002_alter_projeto_horas_totais_realizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='Horas_realizadas',
            field=models.FloatField(default=0),
        ),
    ]
